id: P004421
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:20:05.516508
source_metadata:
  id: bdr:W1KG9277
  title: སྡེ་དགེའི་བསྟན་འགྱུར་དཀར་ཆག་ཞིབ་གསལ་བཀོད་པ།
  author: ''
  volumes:
    aa8b4dd1e34140e3921824e8cf33c63b:
      image_group_id: I1KG9510
      title: ''
      volume_number: 1
      total_pages: 244
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
